name: ProxySuiteBukkit
main: de.sabbertran.proxysuite.bukkit.ProxySuiteBukkit
version: 1.2.5
website: http://www.sabbertran.de
author: Sabbertran
authors: [seyfahni, CryLegend, okx-code]
description: ProxySuite Bukkit handler
softdepend: [WorldEdit, WorldGuard, Vault]
commands:
   bun:
     description: Execute a BungeeCord command as the console or a player
     usage: /bun <player>|CONSOLE <command>
